
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victoralonso
 */
public class Board extends javax.swing.JPanel {
    
    private static int numRows = 75;
    private static int numCols = 50;
    private Snake snake;
    private Food food;
    private Food specialFood;
    private Timer snakeTimer;
    private Timer specialFoodTimer;
    private int DeltaTime;

    
    public static void setNumRows(int numRows) {
        Board.numRows = numRows;
    }

    public static void setNumCols(int numCols) {
        Board.numCols = numCols;
    }

    public static int getRows(){
        return numRows;
    }

    public static int getCols(){
        return numCols;
    }
    
    public int getSquareWidth() {
        return getWidth() / Board.getCols();        
    }
    
    public int getSquareHeight() {
        return getHeight() / Board.getRows();
    }
    
    
    /**
     * Creates new form Board
    */

    public Board() {
        initComponents();
        myInit();
        
        
    }
    
    private void myInit() {
        
    }
    
    public Board(int numRows, int numCols) {
        // Finish this method
    }
    
    public boolean colideFood() {
        // Finish this method
        return false;
    }
    
    public void gameOver() {
        // Finish this method
    }
    
    @Override 
    protected void paintComponent(Graphics g)  {
        // Finish this method
        // Paint the Snake and the food herep
    }
    
    public void paintBoard(Graphics2D g2d) {
        for (int row = 0; row < getRows(); row++) {
            for (int col = 0; col <  getCols(); col++) {
                Util.drawSquare(g2d, row, col, getSquareWidth(), getSquareHeight(), new Color(138, 49, 49));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
